### ISSUE TITLE
WOL over WLAN doesn't work

### ISSUE THREAD

**Issue by The-Paw** [vniehues/homebridge-saphi-tv#3]
**Describe Your Problem:**
Hello...  basically the control works with my PUS7805.  only wol-start does not work via home over wlan.  but basically it works with the device (tested by iOS-App "magic packet")?

**Logs:**

```
6.2.2021, 12:36:55 [7805] Get AmbiHue
6.2.2021, 12:36:55 [7805] Get Active
6.2.2021, 12:37:15 [7805] Sending RemoteInput: 15
6.2.2021, 12:37:15 [7805] WOL-Error: 
6.2.2021, 12:37:15 [7805] set Active => 1
6.2.2021, 12:37:18 (node:9383) UnhandledPromiseRejectionWarning: FetchError: request to http://192.168.178.79:1925/6/input/key failed, reason: connect EHOSTUNREACH 192.168.178.79:1925
6.2.2021, 12:37:18 at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/node-fetch/lib/index.js:1461:11)
6.2.2021, 12:37:18 at ClientRequest.emit (events.js:310:20)
6.2.2021, 12:37:18 at Socket.socketErrorListener (_http_client.js:426:9)
6.2.2021, 12:37:18 at Socket.emit (events.js:310:20)
6.2.2021, 12:37:18 at emitErrorNT (internal/streams/destroy.js:92:8)
6.2.2021, 12:37:18 at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
6.2.2021, 12:37:18 at processTicksAndRejections (internal/process/task_queues.js:84:21)
6.2.2021, 12:37:18 (node:9383) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
6.2.2021, 12:37:18 (node:9383) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
6.2.2021, 12:37:18 [7805] Sending RemoteInput: 8
6.2.2021, 12:37:21 [7805] Sending RemoteInput: 5
6.2.2021, 12:37:21 (node:9383) UnhandledPromiseRejectionWarning: FetchError: request to http://192.168.178.79:1925/6/input/key failed, reason: connect EHOSTUNREACH 192.168.178.79:1925
6.2.2021, 12:37:21 at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/node-fetch/lib/index.js:1461:11)
6.2.2021, 12:37:21 at ClientRequest.emit (events.js:310:20)
6.2.2021, 12:37:21 at Socket.socketErrorListener (_http_client.js:426:9)
6.2.2021, 12:37:21 at Socket.emit (events.js:310:20)
6.2.2021, 12:37:21 at emitErrorNT (internal/streams/destroy.js:92:8)
6.2.2021, 12:37:21 at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
6.2.2021, 12:37:21 at processTicksAndRejections (internal/process/task_queues.js:84:21)
6.2.2021, 12:37:21 (node:9383) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
6.2.2021, 12:37:21 (node:9383) UnhandledPromiseRejectionWarning: FetchError: request to http://192.168.178.79:1925/6/input/key failed, reason: connect EHOSTUNREACH 192.168.178.79:1925
6.2.2021, 12:37:21 at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/node-fetch/lib/index.js:1461:11)
6.2.2021, 12:37:21 at ClientRequest.emit (events.js:310:20)
6.2.2021, 12:37:21 at Socket.socketErrorListener (_http_client.js:426:9)
6.2.2021, 12:37:21 at Socket.emit (events.js:310:20)
6.2.2021, 12:37:21 at emitErrorNT (internal/streams/destroy.js:92:8)
6.2.2021, 12:37:21 at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
6.2.2021, 12:37:21 at processTicksAndRejections (internal/process/task_queues.js:84:21)
6.2.2021, 12:37:21 (node:9383) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
6.2.2021, 12:37:28 [7805] Get AmbiHue
6.2.2021, 12:37:28 [7805] Get Active
6.2.2021, 12:37:30 [7805] set AmbiHue => true
6.2.2021, 12:37:35 [7805] set AmbiHue => true
6.2.2021, 12:37:36 [7805] WOL-Error: 
6.2.2021, 12:37:36 [7805] set Active => 1
6.2.2021, 12:37:47 (node:9383) UnhandledPromiseRejectionWarning: FetchError: request to http://192.168.178.79:1925/6/HueLamp/power failed, reason: connect EHOSTUNREACH 192.168.178.79:1925
6.2.2021, 12:37:47 at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/node-fetch/lib/index.js:1461:11)
6.2.2021, 12:37:47 at ClientRequest.emit (events.js:310:20)
6.2.2021, 12:37:47 at Socket.socketErrorListener (_http_client.js:426:9)
6.2.2021, 12:37:47 at Socket.emit (events.js:310:20)
6.2.2021, 12:37:47 at emitErrorNT (internal/streams/destroy.js:92:8)
6.2.2021, 12:37:47 at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
6.2.2021, 12:37:47 at processTicksAndRejections (internal/process/task_queues.js:84:21)
6.2.2021, 12:37:47 (node:9383) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
6.2.2021, 12:37:50 (node:9383) UnhandledPromiseRejectionWarning: FetchError: request to http://192.168.178.79:1925/6/HueLamp/power failed, reason: connect EHOSTUNREACH 192.168.178.79:1925
6.2.2021, 12:37:50 at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/node-fetch/lib/index.js:1461:11)
6.2.2021, 12:37:50 at ClientRequest.emit (events.js:310:20)
6.2.2021, 12:37:50 at Socket.socketErrorListener (_http_client.js:426:9)
6.2.2021, 12:37:50 at Socket.emit (events.js:310:20)
6.2.2021, 12:37:50 at emitErrorNT (internal/streams/destroy.js:92:8)
6.2.2021, 12:37:50 at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
6.2.2021, 12:37:50 at processTicksAndRejections (internal/process/task_queues.js:84:21)
6.2.2021, 12:37:50 (node:9383) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
6.2.2021, 12:37:51 [7805] set AmbiHue => true
```

**Plugin Config:**

```json

Config:
        {
            "name": "7805",
            "platform": "SaphiTV",
            "input_delay": 650,
            "has_ambihue": true,
            "startup_time": 15,
            "has_ambilight": true,
            "ambi_poweroff": true,
            "ip_adress": "192.168.178.79",
            "channel_setup_popup_time": 2250,
            "ambi_poweron": true,
            "wol_adress": "****",
            "api_port_no": 1925,
            "api_version": 6,
            "plugin_map": {
                "plugin_name": "homebridge-saphi-tv"
            },
            "polling_interval": 40,
            "protocol": "http",
            "timeout": 5,
            "has_tv_channels": true,
            "inputs": []
        }

Any ideas??```

**Screenshots:**
NO
**Environment:**
hoobs
* **Plugin Version**:
* 0.0.27
* 
* **Homebridge Version**: 
* hoobs 3.3.2
* **Node.js Version**: 
* 12.16.3
*

**Comment by vniehues** [comment]
Hey @The-Paw thanks for your submission!
I see you redacted your WOL-Address. Please make sure it's in the following format: 
```
wol://<your-mac-address>
e.g:
wol://11:22:33:44:55:66
```

Your WOL-Error leads me to believe that this is the issue. The packet does not get send. 
Regardless if the TV turns on or not, when the package is sent successfully, the plugin will report "WOL-OK!".

Please report back if adjusting your WOL-Format solves the issue. 
Otherwise we need to look over it again.

**Comment by The-Paw** [comment]
> Hey @The-Paw thanks for your submission!
> I see you redacted your WOL-Address. Please make sure it's in the following format:
> 
> ```
> wol://<your-mac-address>
> e.g:
> wol://11:22:33:44:55:66
> ```
> 
> Your WOL-Error leads me to believe that this is the issue. The packet does not get send.
> Regardless if the TV turns on or not, when the package is sent successfully, the plugin will report "WOL-OK!".
> 
> Please report back if adjusting your WOL-Format solves the issue.
> Otherwise we need to look over it again.

Of course I don't post my complete MAC address here;) In the original config, of course, is the complete one.

**Comment by vniehues** [comment]
No worries, I didn't mean that you should share it. [(Although it's not really a concern)](https://security.stackexchange.com/questions/67893/is-it-dangerous-to-post-my-mac-address-publicly)
I only want you to make sure that the address is in **exactly** the format I provided.

Basically if "WOL-Error:" shows no Error-Message behind it, the package never went out. 
It aborted the request because the address was not in the expected format. 
It's either missing the "wol://" at the beginning or it's not formatted correctly. 
It _might_ also be a bug on my side. But the error message leads me to believe that the issue comes from a wrong format/address.

There should be a line in your logs like this: `"calling WOL with URL <WOL-URL>"`. 
If you feel comfortable sharing it here or sending it to me by mail (info@vniehues.de) that could help really much!

**Comment by The-Paw** [comment]
> No worries, I didn't mean that you should share it. [(Although it's not really a concern)](https://security.stackexchange.com/questions/67893/is-it-dangerous-to-post-my-mac-address-publicly)
> I only want you to make sure that the address is in **exactly** the format I provided.
> 
> Basically if "WOL-Error:" shows no Error-Message behind it, the package never went out.
> It aborted the request because the address was not in the expected format.
> It's either missing the "wol://" at the beginning or it's not formatted correctly.
> It _might_ also be a bug on my side. But the error message leads me to believe that the issue comes from a wrong format/address.
> 
> There should be a line in your logs like this: `"calling WOL with URL <WOL-URL>"`.
> If you feel comfortable sharing it here or sending it to me by mail ([info@vniehues.de](mailto:info@vniehues.de)) that could help really much!

The: // are not adopted. Enter the MAC in the hoobs config page and then the config is missing :// .. maybe this is a plug-in bug, or maybe even directly from hoobs. At least it works now.

Another question still spontaneous .. Channel number for the inputs from the main list or the currently set (in my case a preferred one)? Input setting for HDMI 2 ??

**Comment by vniehues** [comment]
Oh that's good to know! I'm thinking this is a hoobs bug since it works fine in my homebridge. But I'll definately test it and see if i can fix it.
Anyways, I'm glad it now works for you.

Channel number should be for the list thats currently active. 
The plugin just sends out the following key presses: (example Channel with position 83)
Send Key: Watch TV (this activates the tv activity)
Send Key: 8
Send Key: 3
Send Key: Confirm (this makes the TV switch instantly instead of waiting for the input-timeout)

As for your Input settings (I make an entry in the readme for this):
When you press "Watch TV", "Sources", "Cursor Down" you are on the input that the plugin sees as **position 0**.
When you go one to the left you are on **position -1**. When you go one to the right you are on **position 1**.

So if you need to go right 3 times to be on the HDMI2-Input, you need to enter **position: 2**.

Sadly thats the only way to make sure that the TV will always land on the desired input. 
If you need further help with the setup of your Inputs, Channels and Apps, please open a new Issue with the "Support Request" template as I will be closing this one. (Issue seems to be resolved)

Thank you for using my plugin and for submitting this report! :)
