### ISSUE TITLE
Ambilight switch & Volume slider 

### ISSUE THREAD

**Issue by Piit3r** [vniehues/homebridge-saphi-tv#6]
Hi and congrats for your project.

I don't understand why you commented the functions that allow us to turn on/off ambilight and the volume slider in the Home App. 
(in tvAccessory lines 57-69 and 86-99)
You just wrote :
`// TODO: implement get & set with reference to old project.`

But from what i can see, it seems ok, isn't it?

**Comment by vniehues** [comment]
Hi and thank you! :) 

Unfortunately it's not in a working state and because I just copied the code from an old project, I need to make some adjustments so that it works with the new plugin. 

I'm currently gathering some feedback and I will work on the plugin again when I find some time for it. 
Sooner or later the support for the built-in ambilight and support for volume via slider will come :)
